### ISSUE TITLE
Main loop too slow

### ISSUE THREAD

**Issue by konsultaner** [uuf6429/InterExec#7]
I was testing your script with a bat file on windows that just outputted some strings. I found out that only putting the tick-time to 0 would output nerly all lines I echoed. The problem ist that php loops a lot slower then some echos in a bat file. The main loop looses output information when iterating. I tested the same bat-file with thise lines of code and it worked well:

``` bash
@ECHO off
echo hello & echo.world
ECHO "TEST"
ECHO "Line2"
ECHO "%0"
ECHO "%1"
ECHO "%2"
```

``` php
<?php
$cmd = "test\\Mock\\wlanCallCommandMock param1 2";

$descriptorspec = array(
    0 => array("pipe", "r"),   // stdin is a pipe that the child will read from
    1 => array("pipe", "w"),   // stdout is a pipe that the child will write to
    2 => array("pipe", "w")    // stderr is a pipe that the child will write to
);
flush();
$process = proc_open($cmd, $descriptorspec, $pipes, realpath('./'), array());
echo "<pre>";
if (is_resource($process)) {
    $w = array($pipes[0]);
    $r = array($pipes[1],$pipes[2]);
    $e = null;
    $stat = proc_get_status($process);
    // loop on the is_runnning method from InterExec
    while (!(!$stat['running'] || $stat['signaled'] || $stat['stopped'])) {
        $stat = proc_get_status($process);
        var_dump(stream_select($r,$w,$e, null/*, 25000*/));
        print fgets($pipes[1]);
        flush();
    }
}
echo "</pre>";
```

**Comment by uuf6429** [comment]
Hello Richard,

I have yet to test this out. However, as far as I know speed (or actually, delays) shouldn't cause loss of information since the streams should be buffered.

**Comment by konsultaner** [comment]
I just guessed that time is a reason, but the issue might be caused by something else. anyway you loose information when using InterExec. I send about 2 hours trying to fix it, then I decided that you might know why. Thats why I was able to pass a script that actually works
