### ISSUE TITLE
Can't wait for output before inputting something else

### ISSUE THREAD

**Issue by iopq** [uuf6429/InterExec#8]
The interactive session should be this:

name
= my thing
protocol_version
= 2

etc. I need to wait for a line starting with `=` before inputting the next thing, but it seems like this script just spam inputs all the strings and there is no way to tell it to chill out (since PHP_EOL actually results in an empty command error in my script)

**Comment by uuf6429** [comment]
I guess that to do that, `PHP_EOL` ([found here](https://github.com/uuf6429/InterExec/blob/master/src/InterExec.php#L261)) should be configurable.

**Comment by iopq** [comment]
I was thinking if you got `FALSE` you shouldn't send any input. That way scripts can send `''` (empty string) if they want to, but there is a way to avoid sending input if the time is not right.
